### PR TITLE
Fixed Schedule Display for Los Angeles Time Zone

### PR DESCRIPTION
**Pull request by epitaphmike**
Now app displays local time for conference despite your current location.

### CODE REVIEW

**Comment by JedWatson** [comment]
Awesome, thanks @epitaphmike!

**Comment by epitaphmike** [comment]
How long does the code push take? That was a pretty impressive portion of Ram's talk.

**Comment by JedWatson** [comment]
Only a couple of minutes, I just need to get the cli set up on my MacBook :)

**Comment by epitaphmike** [comment]
Awesome. This fix can also be done a lot better to accept a time zone as a property instead of being static. But I was trying to have it fixed before you all were done with lunch!

**Comment by JedWatson** [comment]
It's out! Thanks again, awesome to have that fixed. Your app should restart any moment now.

**Comment by epitaphmike** [comment]
Right before my eyes. That was pretty rad.

**Pull request merged**
